### ISSUE TITLE
Group/ID not found

### ISSUE THREAD

**Issue by MattBixley** [nesi/nesi-ood-jupyterlab-app#1]
Jupyter Terminal 

`id: cannot find name for user ID 957000012
[I have no name!@jupyterlab-atdil9w4 ~]$ `

Appears where running `module avail R-Geo`
`[I have no name!@jupyterlab-atdil9w4 ~]$ module avail R-Geo
groups: cannot find name for group ID 957000012`

But not with `module load XXXX`

**Comment by lbrick** [comment]
This has been resolved with the latest commit

**Comment by MattBixley** [comment]
Confirmed
![image](https://github.com/user-attachments/assets/28ef731f-839a-43ae-9ccf-68badba5cd68)
