### ISSUE TITLE
Server Connection Error

### ISSUE THREAD

**Issue by MattBixley** [nesi/nesi-ood-jupyterlab-app#2]
Server Disconnects
Happened twice while doing install.packages() with R via the terminal. 2nd Terminal opened was also hanging before that. 

It kills the terminals after clicking dismiss.

![image](https://github.com/user-attachments/assets/a0ddedd5-c068-4a07-a24b-b97ed1e5f409)

Note: it's not related to the the install command or the specific package, they have now worked.

**Comment by MattBixley** [comment]
Is there load monitoring on the jupyter app?

Mahuika Jupyter - It caused the connection/dismiss to regularly happen and was turned off. circa late 2022

**Comment by lbrick** [comment]
Checking to see if its the pod itself that is causing this as you might be maxing the resources on that pod

**Comment by lbrick** [comment]
`module load R-Geo
R
install.packages("brms")
Then yes. Yes and for cran mirror select 1`

Steps to reproduce pod load

**Comment by MattBixley** [comment]
Can reproduce at will creating matrices of a known size.

Using the below code and a pod with 2G mem, a 1 GB object is created, the 5GB object cause the dismiss. with a 12GB pod a 10GB matrix is created, creating a 2nd 10GB matrix cause the Dismiss

load and start R in a terminal
`module load R-Geo
R`

Run the R functions to set them up, then run the matrix creations. Total object size is additive. 

`# Function to create a matrix of a specified size in GB
create_matrix <- function(size_gb, bits = 8) {
  # Create the matrix
  matrix <- matrix(1, nrow = floor(1000000/bits) * size_gb, ncol = 1000)
  return(matrix)
}


# Function to convert object size from bytes to gigabytes
size_in_gb <- function(object) {
  size_in_bytes <- as.numeric(object.size(object))
  size_in_gb <- size_in_bytes / (1024^3)
  return(paste0(round(size_in_gb, 2), " GB"))
}


# Create matrices of different sizes
matrix_1gb <- create_matrix(1)
size_in_gb(matrix_1gb)
matrix_5gb <- create_matrix(5)
size_in_gb(matrix_5gb)
matrix_10gb <- create_matrix(10)
size_in_gb(matrix_10gb)
`

**Comment by MattBixley** [comment]
Similar error on Mahuika Jupyter, 4GB session, creates the 1G matrix but gets bus/OOM with the 5G

`# Create matrices of different sizes
matrix_1gb <- create_matrix(1)
size_in_gb(matrix_1gb)
matrix_5gb <- create_matrix(5)
size_in_gb(matrix_5gb)
[1] "0.93 GB"
Bus error
wbn001 ~ $ `

**Comment by MattBixley** [comment]
Replicated on eRI
This is expected behavior - had not seen before, closing with a note we need to add to Troubleshooting Documentaion in NeSI support docs

**Comment by MattBixley** [comment]
replicated with Python at the terminal
